# -*- coding: utf-8 -*-
"""setup_database

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AFCAE2scPkGpMy2gX3esfChNUDkOlvs2
"""

import sqlite3

# Connect to SQLite database
conn = sqlite3.connect('hot_topics.db')
c = conn.cursor()

# Create comments table
c.execute('''
    CREATE TABLE IF NOT EXISTS comments (
        id INTEGER PRIMARY KEY,
        headline TEXT,
        user TEXT,
        comment TEXT,
        sentiment TEXT
    )
''')

# Commit and close connection
conn.commit()
conn.close()

print("Database setup complete.")